application:
  title: Billing-data-Service
  version: 1.0.0
server:
  port: 8081
spring:
  datasource:
    password: xivcuncedWenjugba!@31
    url: jdbc:sqlserver://riturajghoshdbserver.database.windows.net:1433;database=uploaddata;;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: rituraj@riturajghoshdbserver
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      connection-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
